feat: add -raw and also allow interpolanization

diff --git a/ndjson-env b/ndjson-env
--- a/ndjson-env
+++ b/ndjson-env
@@ -2,6 +2,7 @@
 
 OPTIND=1
 FILENAME=''
+RAW=0
 
 show_help() {
     echo "NAME:"
@@ -12,6 +13,7 @@ show_help() {
     echo ""
     echo "GLOBAL OPTIONS:"
     echo "  -f    The file to load environment sets from"
+    echo "  -r    Output raw (for scripting and navi)"
     echo "  -h    Get (this) help"
     echo ""
     echo "ARGUMENTS:"
@@ -20,21 +22,25 @@ show_help() {
     exit 0
 }
 
-while getopts "hf:" opt; do
+while getopts "hrf:" opt; do
     case "$opt" in
         h)
             show_help
             exit 0
             ;;
+        r)
+            RAW=1
+            ;;
         f)  FILENAME="$OPTARG"
             ;;
+        *)
+            echo "INVALID FLAG"
+            exit 1
     esac
 done
 
 shift $(( OPTIND - 1 ))
 ENV_SET="$1"
-
-
 
 if [ "$FILENAME" == '' ]; then
     show_help
@@ -42,20 +48,34 @@ if [ "$FILENAME" == '' ]; then
 fi
 
 if [ "$ENV_SET" == '' ]; then
-    echo "Pass one of the following: "
-    echo ""
+    [ $RAW -eq 0 ] && echo "Pass one of the following: "
+    [ $RAW -eq 0 ] && echo ""
     exec<"$FILENAME"
     while read -r LINE
     do
         NAME=$(echo "$LINE" | jq -r ._name)
         if [[ "$NAME" =~ [a-zA-Z0-9] ]]; then
-            echo " * $NAME"
+            [ $RAW -eq 1 ] && echo "$NAME"
+            [ $RAW -eq 0 ] && echo " * $NAME"
         fi
     done
-    echo ""
+    [ $RAW -eq 0 ] && echo ""
     exit 0
 fi
 
+# == START FUNCTIONS ===========================================================
+
+function infect_line {
+    local RE='(.*)\$\{([A-Z][A-Z0-9]*)\}(.*)'
+    local OUT=$1
+    if [[ $OUT =~ $RE ]]; then
+        local X="${BASH_REMATCH[2]}"
+        OUT="${BASH_REMATCH[1]}${!X}${BASH_REMATCH[3]}"
+    fi
+    echo "$OUT"
+}
+
+# == START OF REAL PROGRAM =====================================================
 
 DONE=0
 while read -r LINE; do
@@ -65,16 +85,17 @@ while read -r LINE; do
         DONE=1
     fi
     if [ "$DONE" -eq 0 ] && [ "$NAME" == "$ENV_SET" ]; then
-        echo "Found: $NAME - Loading Environment"
+        [ $RAW -eq 0 ] && echo "Found: $NAME - Loading Environment"
         KEYS=$(echo "$LINE" | jq keys | jq .[] -r | grep -v _name)
-        echo ""
+        [ $RAW -eq 0 ] && echo ""
         for K in $KEYS; do
-            V=$(echo "$LINE" | jq ".$K" -r)
+            VSRC=$(echo "$LINE" | jq ".$K" -r)
+            V=$(infect_line "$VSRC")
             export "$K"="$V"
-            echo "  $K = $V"
+            [ $RAW -eq 0 ] && echo "  $K = $V"
             DONE=1
         done
-        echo ""
+        [ $RAW -eq 0 ] && echo ""
     fi
 done < "$FILENAME"
 
